DROP DATABASE IF EXISTS similar_properties;
CREATE DATABASE similar_properties;

USE similar_properties;

CREATE TABLE HOST (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name NOT NULL VARCHAR(50)
);

CREATE TABLE PROPERTY (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  location NOT NULL VARCHAR(50),
  rating NOT NULL DECIMAL(3,2) UNSIGNED,
  property_type NOT NULL VARCHAR(25),
  bed_num NOT NULL TINYINT UNSIGNED,
  description NOT NULL VARCHAR(255),
  price_per_night NOT NULL SMALLINT UNSIGNED,
  host_id INT REFERENCES NOT NULL HOST(id)
);

CREATE TABLE PHOTOS (
  id INT NOT NULL PRIMARY KEY,
  src VARCHAR(255) NOT NULL,
  property_id INT NOT NULL REFERENCES PROPERTY(id)
);

CREATE TABLE similarPROPERTIES (
  id INT PRIMARY KEY AUTO_INCREMENT,
  similar_home_1 INT REFERENCES NOT NULL PROPERTY(id),
  similar_home_2 INT REFERENCES NOT NULL PROPERTY(id),
  similar_home_3 INT REFERENCES NOT NULL PROPERTY(id),
  similar_home_4 INT REFERENCES NOT NULL PROPERTY(id),
  similar_home_5 INT REFERENCES PROPERTY(id),
  similar_home_6 INT REFERENCES PROPERTY(id),
  similar_home_7 INT REFERENCES PROPERTY(id),
  similar_home_8 INT REFERENCES PROPERTY(id),
  similar_home_9 INT REFERENCES PROPERTY(id),
  similar_home_10 INT REFERENCES PROPERTY(id),
  similar_home_11 INT REFERENCES PROPERTY(id),
  similar_home_12 INT REFERENCES PROPERTY(id),
  property_id INT REFERENCES NOT NULL PROPERTY(id)
);